[build.environment]
GO_VERSION = "1.26.1"
HUGO_VERSION = "0.160.0"
TZ = "America/New_York"

[build]
publish = "public"
command = """\
  git config core.quotepath false && \
  hugo build --gc --minify --baseURL "${URL}"
  """